// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uuid.proto

/*
Package pbuuid is a generated protocol buffer package.

It is generated from these files:
	uuid.proto

It has these top-level messages:
	UUID
*/
package pbuuid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// <Documentation of the message>
type UUID struct {
	// <Documentation of the bytes field>
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (m *UUID) Reset()                    { *m = UUID{} }
func (m *UUID) String() string            { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()               {}
func (*UUID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UUID) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
	proto.RegisterType((*UUID)(nil), "pbuuid.UUID")
}

func init() { proto.RegisterFile("uuid.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0xcd, 0x4c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48, 0x02, 0xf1, 0x94, 0x64, 0xb8, 0x58,
	0x42, 0x43, 0x3d, 0x5d, 0x84, 0x44, 0xb8, 0x58, 0x93, 0x2a, 0x4b, 0x52, 0x8b, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x78, 0x82, 0x20, 0x1c, 0x27, 0xb9, 0x28, 0x99, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24,
	0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0x9c, 0xfc, 0x94, 0xd4, 0xa2, 0xd2, 0xbc, 0xbc, 0xd4, 0x22, 0x7d,
	0x88, 0xee, 0x24, 0x36, 0xb0, 0x61, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xf7, 0xe7,
	0x10, 0x5a, 0x00, 0x00, 0x00,
}
